name: Add latest tag to new release

#on:
#  release:
#    types: [published]

on: [push]

jobs:
  run:
    name: Run latest-tag action
    runs-on: ubuntu-latest
    steps:
      - name: Run latest-tag
        uses: EndBug/latest-tag@latest
